### ISSUE TITLE
Better initialisation

### ISSUE THREAD

**Issue by skogsmaskin** [skogsmaskin/slate-insert-block-on-enter#1]
The initialisation of the plugin (block properties) is not yet as I want, because there are some bugs in Slate when `Block.create` is used in combination with `insertNodeByKey`.

If I create the block to insert with `Block.create({type: 'paragraph'})`

`insertBlock` inserts the block with one node in `.nodes` (empty text node).
`insertNodeByKey` inserts a block with empty `.nodes` - causing side effects in the rendering of node.

So what I have to do for now is to create the block with `Raw.deserializeNode(blockInputProps)` where `blockInputProps` is like `{kind: 'block', type: 'paragraph', nodes: [{kind: 'text', text: '', ranges: []}]}`

This makes `insertBlock` and `insertNodeByKey` both work as expected.

**Comment by oyeanuj** [comment]
@skogsmaskin Is this still on the radar now that the slate issue seems to have been solved?

**Comment by skogsmaskin** [comment]
This is now fixed. The plugin now takes the same kind of parameter as ``transform.insertBlock``. Either a object with block properties, or just a string. It is also backward compatible.
