### ISSUE TITLE
Incompatible with latest Slate

### ISSUE THREAD

**Issue by steobrien** [skogsmaskin/slate-insert-block-on-enter#3]
I believe this doesn’t work for version 0.29 and up. (See https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md, there was a major change including a rename from `state` to `value` in 0.29).

Do you have any plans to update?

**Comment by skogsmaskin** [comment]
Refactored for version 0.29 and up.

Unfortunately void nodes are no longer able to have the cursor collapsed in either start or end of the void node (it's now just on), so the logic where I inserted the new node below or over dynamically based on cursor position had to be removed. Now it will insert it above if the void node is at the absolute top of the document, or below in every other case.
